AÑO 2008
```{r}
library(htmltab)
linkpublico= 'https://datosmacro.expansion.com/estado/gasto?anio=2008'
linkpath='//*[@id="node-10595"]/div[4]/div'
p2008 = htmltab(doc = linkpublico, 
                which =linkpath)
```



```{r}
dim(p2008)
```

```{r}
head(p2008)
```

```{r}
tail(p2008)
```

```{r}
names(p2008)
```

```{r}
p2008[,c(2,3,4,6,7,8)]=NULL

```
```{r}
names(p2008)[1]= 'Pais'
```
```{r}
names(p2008)[2]= 'GP2008'
```


```{r}
str(p2008)
```



```{r}
p2008$`GP2008` = gsub("\\%", "", p2008$`GP2008`)
p2008$`GP2008` = gsub("\\,", ".", p2008$`GP2008`)
```

```{r}
str(p2008)
```


```{r}
p2008 = p2008[complete.cases(p2008),]
```
```{r}
str(p2008)
```


```{r}
p2008$`GP2008`=as.numeric(p2008$`GP2008`)
```

```{r}
str(p2008)
```

 
```{r}
p2008$`Pais` = gsub("\\[+]", " ", p2008$`Pais`)
```
```{r}
p2008$`Pais` = gsub("\\+", "", p2008$`Pais`)
```

```{r}
p2008$`Pais` = gsub("\\[", "", p2008$`Pais`)
```

```{r}
p2008$`Pais` = gsub("\\]", "", p2008$`Pais`)
```



```{r}
str(p2008)
```




```{r}
row.names(p2008)=NULL
```



```{r}
p2008=p2008[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
row.names(p2008)=NULL
```

```{r}
p2008[p2008$Pais=="Benín ",'Pais']="Benin"
p2008[p2008$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2008[p2008$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2008[p2008$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2008[p2008$Pais=="Camerún ",'Pais']="Camerun"
p2008[p2008$Pais=="Etiopía ",'Pais']="Etiopia"
p2008[p2008$Pais=="Gabón ",'Pais']="Gabon"
p2008[p2008$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2008[p2008$Pais=="Malí ",'Pais']="Mali"
p2008[p2008$Pais=="Níger ",'Pais']="Niger"
p2008[p2008$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2008[p2008$Pais=="Sudán ",'Pais']="Sudan"
p2008[p2008$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2008[p2008$Pais=="Túnez ",'Pais']="Túnez"
```


AÑO 2009
```{r}
library(htmltab)
link2009= 'https://datosmacro.expansion.com/estado/gasto?anio=2009'
linkpath2009= '//*[@id="node-10595"]/div[4]/div/div[2]'
p2009= htmltab(doc = link2009,
                     which = linkpath2009)
 
```

```{r}
dim(p2009)
```
```{r}
head(p2009)
```
```{r}
tail(p2009)
```

```{r}
names(p2009)
```

```{r}
p2009[,c(2,3,4,6,7,8)]=NULL
```
```{r}
names(p2009)[1]= 'Pais'
```
```{r}
names(p2009)[1]= 'Pais'
```

```{r}
names(p2009)[2]= 'GP2009'
```


```{r}
str(p2009)
```
```{r}
 p2009$`GP2009` = gsub("\\%", "", p2009$`GP2009`)
```
```{r}
 p2009$`GP2009` = gsub("\\,", ".", p2009$`GP2009`)
```

```{r}
p2009$`Pais` = gsub("\\[+]", " ", p2009$`Pais`)
```
```{r}
p2009$`Pais` = gsub("\\+", "", p2009$`Pais`)
```

```{r}
p2009$`Pais` = gsub("\\[", "", p2009$`Pais`)
```

```{r}
p2009$`Pais` = gsub("\\]", "", p2009$`Pais`)
```
```{r}
p2009 = p2009[complete.cases(p2009),]
```
```{r}
str(p2009)
```
```{r}
p2009 = p2009[complete.cases(p2009),]
```

```{r}
p2009$`GP2009`=as.numeric(p2009$`GP2009`)
```

```{r}
str(p2009)
```
```{r}
row.names(p2009)=NULL
```

```{r}
p2009=p2009[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2009[p2009$Pais=="Benín ",'Pais']="Benin"
p2009[p2009$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2009[p2009$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2009[p2009$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2009[p2009$Pais=="Camerún ",'Pais']="Camerun"
p2009[p2009$Pais=="Etiopía ",'Pais']="Etiopia"
p2009[p2009$Pais=="Gabón ",'Pais']="Gabon"
p2009[p2009$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2009[p2009$Pais=="Malí ",'Pais']="Mali"
p2009[p2009$Pais=="Níger ",'Pais']="Niger"
p2009[p2009$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2009[p2009$Pais=="Sudán ",'Pais']="Sudan"
p2009[p2009$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2009[p2009$Pais=="Túnez ",'Pais']="Túnez"
```

```{r}
row.names(p2009)=NULL
```
AÑO 2010

```{r}
library(htmltab)
link2010= 'https://datosmacro.expansion.com/estado/gasto?anio=2010'
linkpath2010='//*[@id="tb1"]'
p2010 = htmltab(doc =  link2010,
                      which = linkpath2010)
```
```{r}
dim(p2010)
```
```{r}
head(p2010)
```
```{r}
tail(p2010)
```
```{r}
names(p2010)
```
```{r}
p2010[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2010)[1]= 'Pais'
```
```{r}
names(p2010)[2]= 'GP2010'
```
```{r}
str(p2010)
```
```{r}
 p2010$`GP2010` = gsub("\\%", "", p2010$`GP2010`)
```
```{r}
 p2010$`GP2010` = gsub("\\,", ".", p2010$`GP2010`)
```


```{r}
p2010$`Pais` = gsub("\\[+]", " ", p2010$`Pais`)
```
```{r}
p2010$`Pais` = gsub("\\+", "", p2010$`Pais`)
```

```{r}
p2010$`Pais` = gsub("\\[", "", p2010$`Pais`)
```

```{r}
p2010$`Pais` = gsub("\\]", "", p2010$`Pais`)
```
```{r}
p2010 = p2010[complete.cases(p2010),]
```
```{r}
str(p2010)
```
```{r}
p2010 = p2010[complete.cases(p2010),]
```

```{r}
p2010$`GP2010`=as.numeric(p2010$`GP2010`)
```

```{r}
str(p2010)
```
```{r}
row.names(p2010)=NULL
```

```{r}
p2010=p2010[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2010[p2010$Pais=="Benín ",'Pais']="Benin"
p2010[p2010$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2010[p2010$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2010[p2010$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2010[p2010$Pais=="Camerún ",'Pais']="Camerun"
p2010[p2010$Pais=="Etiopía ",'Pais']="Etiopia"
p2010[p2010$Pais=="Gabón ",'Pais']="Gabon"
p2010[p2010$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2010[p2010$Pais=="Malí ",'Pais']="Mali"
p2010[p2010$Pais=="Níger ",'Pais']="Niger"
p2010[p2010$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2010[p2010$Pais=="Sudán ",'Pais']="Sudan"
p2010[p2010$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2010[p2010$Pais=="Túnez ",'Pais']="Túnez"
```

```{r}
row.names(p2010)=NULL
```
AÑO 2011
```{r}
library(htmltab)
link2011= 'https://datosmacro.expansion.com/estado/gasto?anio=2011'
linkpath2011='//*[@id="tb1"]'
p2011 = htmltab(doc =  link2011,
                      which = linkpath2011)
          
```
```{r}
dim(p2011)
```
```{r}
head(p2011)
```
```{r}
tail(p2011)
```
```{r}
names(p2011)
```

```{r}
p2011[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2011)[1]= 'Pais'
```
```{r}
names(p2011)[2]= 'GP2011'
```

```{r}
str(p2011)
```

```{r}
p2011$`GP2011` = gsub("\\%", "", p2011$`GP2011`)
p2011$`GP2011` = gsub("\\,", ".", p2011$`GP2011`)
p2011$`Pais` = gsub("\\[+]", " ", p2011$`Pais`)
p2011$`Pais` = gsub("\\+", "", p2011$`Pais`)
p2011$`Pais` = gsub("\\[", "", p2011$`Pais`)
p2011$`Pais` = gsub("\\]", "", p2011$`Pais`)
```
```{r}
p2011 = p2011[complete.cases(p2011),]
```


```{r}
 p2011$`GP2011` = gsub("\\%", "", p2011$`GP2011`)
```

```{r}
str(p2011)
```


```{r}
p2011$`GP2011`=as.numeric(p2011$`GP2011`)
```

```{r}
str(p2011)
```

```{r}
row.names(p2011)=NULL
```

```{r}
p2011=p2011[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2011[p2011$Pais=="Benín ",'Pais']="Benin"
p2011[p2011$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2011[p2011$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2011[p2011$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2011[p2011$Pais=="Camerún ",'Pais']="Camerun"
p2011[p2011$Pais=="Etiopía ",'Pais']="Etiopia"
p2011[p2011$Pais=="Gabón ",'Pais']="Gabon"
p2011[p2011$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2011[p2011$Pais=="Malí ",'Pais']="Mali"
p2011[p2011$Pais=="Níger ",'Pais']="Niger"
p2011[p2011$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2011[p2011$Pais=="Sudán ",'Pais']="Sudan"
p2011[p2011$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2011[p2011$Pais=="Túnez ",'Pais']="Túnez"
```

```{r}
row.names(p2011)=NULL
```



AÑO 2012
```{r}
library(htmltab)
link2012= 'https://datosmacro.expansion.com/estado/gasto?anio=2012'
linkpath2012='//*[@id="tb1"]'
p2012 = htmltab(doc =  link2012,
                      which = linkpath2012)
          
```
```{r}
dim(p2012)
```
```{r}
head(p2012)
```
```{r}
tail(p2012)
```
```{r}
names(p2012)
```

```{r}
p2012[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2012)[1]= 'Pais'
```
```{r}
names(p2012)[2]= 'GP2012'
```
```{r}
str(p2012)
```

```{r}
p2012$`GP2012` = gsub("\\%", "", p2012$`GP2012`)
p2012$`GP2012` = gsub("\\,", ".", p2012$`GP2012`)
p2012$`Pais` = gsub("\\[+]", " ", p2012$`Pais`)
p2012$`Pais` = gsub("\\+", "", p2012$`Pais`)
p2012$`Pais` = gsub("\\[", "", p2012$`Pais`)
p2012$`Pais` = gsub("\\]", "", p2012$`Pais`)
```
```{r}
p2012 = p2012[complete.cases(p2012),]
```
```{r}
str(p2012)
```

```{r}
p2012$`GP2012`=as.numeric(p2012$`GP2012`)
```

```{r}
str(p2012)
```


```{r}
row.names(p2012)= NULL
```

```{r}
p2012=p2012[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2012[p2012$Pais=="Benín ",'Pais']="Benin"
p2012[p2012$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2012[p2012$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2012[p2012$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2012[p2012$Pais=="Camerún ",'Pais']="Camerun"
p2012[p2012$Pais=="Etiopía ",'Pais']="Etiopia"
p2012[p2012$Pais=="Gabón ",'Pais']="Gabon"
p2012[p2012$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2012[p2012$Pais=="Malí ",'Pais']="Mali"
p2012[p2012$Pais=="Níger ",'Pais']="Niger"
p2012[p2012$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2012[p2012$Pais=="Sudán ",'Pais']="Sudan"
p2012[p2012$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2012[p2012$Pais=="Túnez ",'Pais']="Túnez"
```
```{r}
row.names(p2012)=NULL

```

AÑO 2013

```{r}
library(htmltab)
link2013= 'https://datosmacro.expansion.com/estado/gasto?anio=2013'
linkpath2013='//*[@id="node-10595"]/div[4]/div/div[2]'
p2013 = htmltab(doc =  link2013,
                      which = linkpath2013)
```
```{r}
dim(p2013)
```
```{r}
head(p2013)
```
```{r}
tail(p2013)
```
```{r}
names(p2013)
```

```{r}
p2013[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2013)[1]= 'Pais'
```
```{r}
names(p2013)[2]= 'GP2013'
```
```{r}
str(p2013)
```

```{r}
 p2013$`GP2013` = gsub("\\%", "", p2013$`GP2013`)
```
```{r}
 p2013$`GP2013` = gsub("\\,", ".", p2013$`GP2013`)
```
```{r}
p2013$`Pais` = gsub("\\[+]", " ", p2013$`Pais`)
```
```{r}
p2013$`Pais` = gsub("\\+", "", p2013$`Pais`)
```

```{r}
p2013$`Pais` = gsub("\\[", "", p2013$`Pais`)
```

```{r}
p2013$`Pais` = gsub("\\]", "", p2013$`Pais`)
```
```{r}
p2013 = p2013[complete.cases(p2013),]
```
```{r}
str(p2013)
```

```{r}
p2013$`GP2013`=as.numeric(p2013$`GP2013`)
```

```{r}
str(p2013)
```


```{r}
row.names(p2013)= NULL
```

```{r}
p2013=p2013[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2013[p2013$Pais=="Benín ",'Pais']="Benin"
p2013[p2013$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2013[p2013$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2013[p2013$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2013[p2013$Pais=="Camerún ",'Pais']="Camerun"
p2013[p2013$Pais=="Etiopía ",'Pais']="Etiopia"
p2013[p2013$Pais=="Gabón ",'Pais']="Gabon"
p2013[p2013$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2013[p2013$Pais=="Malí ",'Pais']="Mali"
p2013[p2013$Pais=="Níger ",'Pais']="Niger"
p2013[p2013$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2013[p2013$Pais=="Sudán ",'Pais']="Sudan"
p2013[p2013$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2013[p2013$Pais=="Túnez ",'Pais']="Túnez"
```
```{r}
row.names(p2013)=NULL
```

AÑO 2014

```{r}
library(htmltab)
link2014= 'https://datosmacro.expansion.com/estado/gasto?anio=2014'
linkpath2014='//*[@id="tb1"]'
p2014 = htmltab(doc =  link2014,
                      which = linkpath2014)
          
```
```{r}
dim(p2014)
```
```{r}
head(p2014)
```
```{r}
tail(p2014)
```
```{r}
names(p2014)
```

```{r}
p2014[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2014)[1]= 'Pais'
```
```{r}
names(p2014)[2]= 'GP2014'
```
```{r}
 p2014$`GP2014` = gsub("\\%", "", p2014$`GP2014`)
```
```{r}
 p2014$`GP2014` = gsub("\\,", ".", p2014$`GP2014`)
```
```{r}
p2014$`Pais` = gsub("\\[+]", " ", p2014$`Pais`)
```
```{r}
p2014$`Pais` = gsub("\\+", "", p2014$`Pais`)
```

```{r}
p2014$`Pais` = gsub("\\[", "", p2014$`Pais`)
```

```{r}
p2014$`Pais` = gsub("\\]", "", p2014$`Pais`)
```
```{r}
p2014 = p2014[complete.cases(p2014),]
```
```{r}
str(p2014)
```

```{r}
p2014$`GP2014`=as.numeric(p2014$`GP2014`)
```

```{r}
str(p2014)
```

```{r}
row.names(p2014)= NULL
```

```{r}
p2014=p2014[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2014[p2014$Pais=="Benín ",'Pais']="Benin"
p2014[p2014$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2014[p2014$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2014[p2014$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2014[p2014$Pais=="Camerún ",'Pais']="Camerun"
p2014[p2014$Pais=="Etiopía ",'Pais']="Etiopia"
p2014[p2014$Pais=="Gabón ",'Pais']="Gabon"
p2014[p2014$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2014[p2014$Pais=="Malí ",'Pais']="Mali"
p2014[p2014$Pais=="Níger ",'Pais']="Niger"
p2014[p2014$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2014[p2014$Pais=="Sudán ",'Pais']="Sudan"
p2014[p2014$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2014[p2014$Pais=="Túnez ",'Pais']="Túnez"
```
```{r}
row.names(p2014)=NULL
```

AÑO 2015
```{r}
library(htmltab)
link2015= 'https://datosmacro.expansion.com/estado/gasto?anio=2015'
linkpath2015='//*[@id="tb1"]'
p2015 = htmltab(doc =  link2015,
                      which = linkpath2015)
          
```
```{r}
dim(p2015)
```
```{r}
head(p2015)
```
```{r}
tail(p2015)
```
```{r}
names(p2015)
```

```{r}
p2015[,c(2,3,4,5,7,8,9)]=NULL
```
```{r}
names(p2015)[1]= 'Pais'
```


```{r}
names(p2015)[2]= 'GP2015'
```
```{r}
str(p2015)
```

```{r}
p2015$`GP2015` = gsub("\\%", "", p2015$`GP2015`)
p2015$`GP2015` = gsub("\\,", ".", p2015$`GP2015`)
p2015$`Pais` = gsub("\\[+]", " ", p2015$`Pais`)
p2015$`Pais` = gsub("\\+", "", p2015$`Pais`)
p2015$`Pais` = gsub("\\[", "", p2015$`Pais`)
p2015$`Pais` = gsub("\\]", "", p2015$`Pais`)
```



```{r}
p2015 = p2015[complete.cases(p2015),]
```
```{r}
str(p2015)
```


```{r}
p2015$`GP2015`=as.numeric(p2015$`GP2015`)
```

```{r}
str(p2015)
```




```{r}
row.names(p2015)= NULL
```

```{r}
p2015=p2015[c(15,24,27,28,34,38,39,40,42,44,47,50,54,57,58,59,63,66,67,68,69,72,87,91,100,101,105,106,109,112,115,117,119,122,123,124,125,145,148,149,154,156,158,161,162,163,168,173,175,184,185),]
```
```{r}
p2015[p2015$Pais=="Benín ",'Pais']="Benin"
p2015[p2015$Pais=="República Democrática del Congo ",'Pais']="Republica Democratica del Congo"
p2015[p2015$Pais=="República Centroafricana ",'Pais']="Republica Centroafricana"
p2015[p2015$Pais=="República del Congo ",'Pais']="Republica del Congo"
p2015[p2015$Pais=="Camerún ",'Pais']="Camerun"
p2015[p2015$Pais=="Etiopía ",'Pais']="Etiopia"
p2015[p2015$Pais=="Gabón ",'Pais']="Gabon"
p2015[p2015$Pais=="Guinea-Bisáu ",'Pais']="Guinea Bisau"
p2015[p2015$Pais=="Malí ",'Pais']="Mali"
p2015[p2015$Pais=="Níger ",'Pais']="Niger"
p2015[p2015$Pais=="Sudáfrica ",'Pais']="Sudafrica"
p2015[p2015$Pais=="Sudán ",'Pais']="Sudan"
p2015[p2015$Pais=="Santo Tomé y Príncipe ",'Pais']="Santo Tome y Principe "
p2015[p2015$Pais=="Túnez ",'Pais']="Túnez"
```
```{r}
row.names(p2015)=NULL
```


AHORA JUNTAR TODO


```{r}
invpublica=cbind(p2008,p2009,p2010,p2011,p2012,p2013,p2014,p2015)
```
```{r}
names(invpublica)
```
```{r}
invpublica[,c(3,5,7,9,11,13,15)]=NULL
```


```{r}
str(invpublica)
```

```{r}
invpublica$prom = rowMeans(invpublica[,2:9], na.rm = TRUE)
```

